### ISSUE TITLE
AWS S3 - lack of data compression

### ISSUE THREAD

**Issue by Suqu13** [bluedenim/log4j-s3-search#104]
I noticed that the `s3Compression` flag is not used within `appender-log4j2`. I suppose that it is omitted in the [given method](https://github.com/bluedenim/log4j-s3-search/blob/master/appender-log4j2/src/main/java/com/van/logging/log4j2/Log4j2AppenderBuilder.java#L152). Using `config.setCompressionEnabled(s3Compression)` will solve the problem. 

I suggest also to add additional flag that cooperates with `s3Comporession` to give users choice to decide if they want to use `.gz` file extension or not. A lot of AWS resources, like Athena, work well with compressed files but their names have to contain the suffix.

**Comment by bluedenim** [comment]
Thanks. I'll take a look.

**Comment by bluedenim** [comment]
Release 3.1.2 fixes the bug in Log4j2 appender builder to recognize the s3Compress property. It was missing a line before. 

I'll start 3.2.0 to add a property to append a `.gz` to the file extension when using compression

**Comment by bluedenim** [comment]
Release 3.2.0 now also includes a new configuration key for S3 (`s3KeyGzSuffixEnabled`) to append `.gz` to the key name.
