### ISSUE TITLE
Thread pool executer shutdown not being called. 

### ISSUE THREAD

**Issue by krishamar91** [bluedenim/log4j-s3-search#120]
Hi,

Thread pool shutdown in LoggingEventCache class is not been called during shutdown hook in Log4j2Appender class. This is causing thread leaks and Apache tomcat is not stopping when a stop command is been sent, every time I have to force kill the tomcat process. 

Can you please update the shutdown hook to call LoggingEventCache .shutdown()

**Comment by bluedenim** [comment]
Thanks! I'll look into it. May even help with https://github.com/bluedenim/log4j-s3-search/issues/109

**Comment by bluedenim** [comment]
Release 3.6.0 should have the fix. Thanks much for the call-out!

**Comment by krishamar91** [comment]
Thank You  Van.
