### ISSUE TITLE
Security dependencies bump

### ISSUE THREAD

**Issue by vr** [bluedenim/log4j-s3-search#131]
Hello, 

[Airbyte](https://github.com/airbytehq/airbyte/) use your project for some things and our security tools are reporting you miss some security dependencies update, at least the Elasticsearch one (elasticsearch-rest-high-level-client), 7.11 is End Of Support since a month, and you should move to latest 7.X (7.17.6 at this time)

I have tried enabling dependabot on my fork of your project and it follows automatically this kind of upgrade, maybe you should investigate enabling it on yours ?

Thanks for your help in fixing this.

**Comment by bluedenim** [comment]
Thanks. Working on https://github.com/bluedenim/log4j-s3-search/pull/132 to do this.

**Comment by bluedenim** [comment]
Release 4.1.0 now uses elasticsearch 7.17.6
