### ISSUE TITLE
Call to Exception.printStackTrace() causes Log4j2 to split stacktrace logs

### ISSUE THREAD

**Issue by kylelyk** [bluedenim/log4j-s3-search#136]
In `com.van.logging.LoggingEventCache.publishEventsFromFile(...)`, there’s a call to `t.printStackTrace()` which causes Log4j2 to create a log entry per stacktrace element in the printed exception. That is because the underlying implementation of `java.lang.Throwable.printStackTrace()` prints to system error one line at a time. It would be preferable to log these exceptions using a Log4j2 logger so it automatically gets formatted correctly.

**Comment by bluedenim** [comment]
Thanks! I'll look into it.

**Comment by bluedenim** [comment]
Release 5.0.0 has the changes to now use the logger `com.van.logging.VansLogger` for logging. You can configure this logger to whatever appender you choose.
