### ISSUE TITLE
Support to get values for log4j2Appender configurations from environment variables

### ISSUE THREAD

**Issue by kamleshmsharma** [bluedenim/log4j-s3-search#151]
I run my apps in a containers where I have access to environment variables so that I can inject aws configurations, s3 configurations, s3 path and logFileName etc during startup in the log4j2.xml . 

On checking the log4j2 official documentation I found "Log4j2 Lookups" 
 https://logging.apache.org/log4j/2.x/manual/lookups.html#environment-lookup

Do we have similar support, so that we can inject configurations like this in the Log4j2Appender??

These configurations are environment specific for my application

```
<Log4j2Appender name="Log4j2Appender">
			<PatternLayout pattern="%d{HH:mm:ss,SSS} [%t] %-5p %c{36} - %m%n"/>
			<verbose>false</verbose>
			<!--  Number of messages (lines of log) to buffer before publishing out  -->
			<stagingBufferSize>$${env:LOG4J_BUFFER_SIZE}</stagingBufferSize>
			<!-- <stagingBufferAge>15</stagingBufferAge> -->
			<s3Bucket>$${env:S3_LOGGING_BUCKET}</s3Bucket>
			<s3Path>/api/logs/</s3Path>
			<s3PathStyleAccess>true</s3PathStyleAccess>
			<s3Compression>true</s3Compression>
			<s3AwsKey>$${env:AWS_ACCESS_KEY}</s3AwsKey>
			<s3AwsSecret>$${env:AWS_SECRET_KEY}</s3AwsSecret>
			<s3Region>$${env:AWS_REGION}</s3Region>
		</Log4j2Appender>
```

**Comment by bluedenim** [comment]
If you want to use environment variables, such as:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_DEFAULT_REGION`

All you have to do (after confirming that they are set correctly) is **remove** the configuration for `s3AwsKey`, `s3AwsSecret`, and `s3Region`.

Just use this:
```
<Log4j2Appender name="Log4j2Appender">
			<PatternLayout pattern="%d{HH:mm:ss,SSS} [%t] %-5p %c{36} - %m%n"/>
			<verbose>false</verbose>
			<!--  Number of messages (lines of log) to buffer before publishing out  -->
			<stagingBufferSize>$${env:LOG4J_BUFFER_SIZE}</stagingBufferSize>
			<!-- <stagingBufferAge>15</stagingBufferAge> -->
			<s3Bucket>$${env:S3_LOGGING_BUCKET}</s3Bucket>
			<s3Path>/api/logs/</s3Path>
			<s3PathStyleAccess>true</s3PathStyleAccess>
			<s3Compression>true</s3Compression>
		</Log4j2Appender>
```

**Comment by KamleshAtTray** [comment]
thanks @bluedenim. 1 more question, what would be the best combination of stagingBufferSize and stagingBufferAge so that I can files of reasonable size uploaded to s3 bucket. 

Now I am using the bufferAge=1 and bufferSize=100. But that configuration creates many small size files of few bytes to few kbs. These small chunks are not manageable when some dev asks for logs for a historical date as they are accustomed to seeing files which are few Mbs

**Comment by bluedenim** [comment]
You should not use both `stagingBufferAge` and `stagingBufferSize` at the same time.

Depending on the logging behavior of your app, these two offer different ways to buffer:
- `stagingBufferSize`: this is the number of log events to buffer before flushing to S3. If you set this to 100, then every 100 log events will be pushed to S3 in one "file."
- `stagingBufferAge`: this is the number of minutes to wait before flushing whatever is in the buffer so far (even if it's only one event).

If you use both (stagingBufferSize=1; stagingBufferSize=100 as you described), then `stagingBufferSize` is ignored, and basically it will publish to S3 every minute.

From your description, it sounds like you don't have a high frequency of logs. I suggest using just `stagingBufferSize=500` (remove `stagingBufferAge`) from your settings. You can adjust the number lower if your logs files are too large or higher if they are still too small.

**Comment by kamleshmsharma** [comment]
@bluedenim I suppose I'll have to proceed with setting stagingBufferAge to one minute due to irregular frequency of log events. 

Can stagingBufferAge have a value lower than 1 minute and will the app performance suffer if staggingBufferAge is set to less than 1 minute or 1 minute? 

Will everything in the buffer be flushed by your implementation before it shuts down? Have you put this test case to the test while you were developing? 

The requests that the app receives at any one time determine how frequently events are logged. Therefore, if the threshold is not exceeded, employing stagingBufferAge can prevent log events from flushing to S3. Do I have this right?

**Comment by bluedenim** [comment]
There are some overhead in maintaining the cache of events and flushing the cache to S3 or whatever storage configured. If the values `stagingBufferAge `or `stagingBufferSize `were set too low, you may see either a continuous thrashing or resources and/or ultimately a rise in resource usage if log events are accumulating faster than the effective publish rate. Constant calls to the respective services publish content also incur usage fees.

There is a shutdown hook installed to flush the caches. In most typical cases when the process gets a SIGTERM, the cache should be published fine. Of course, if it gets a SIGKILL, then there is nothing we can do.

**Comment by bluedenim** [comment]
Sorry. I think I missed your last question there.

Yes. If stagingBufferSize is not reached, the events will not be published unless the app is closing.


________________________________

**Comment by bluedenim** [comment]
In short:
If you want consistent number of events per batch at the risk of delayed publishes when log frequency is low, use stagingBufferSize.

If you want consistent frequency of publishes at the risk of highly fluctuating batch sizes corresponding to the bursty log frequency, use stagingBufferAge.


________________________________

**Comment by bluedenim** [comment]
Thinking about it more, perhaps a combination of both concepts would be useful. It'd be a straight forward change, I think, to add the max size logic to the time-based buffer.

I will consider adding it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
