### ISSUE TITLE
Spark job Running forever after completed

### ISSUE THREAD

**Issue by sontt710** [bluedenim/log4j-s3-search#155]
Hello,

I try to use appender with the following version to submit spark job (spark-pi example) on k8s, but the job running forever and not shutdown after complete, can you help me to check

# Version
Spark 3.3.4
Log4j2
Appender 5.3.2
hadoop-aws-3.3.2.jar
aws-java-sdk-bundle-1.11.1026.jar
aws-java-sdk-s3-1.12.772.jar

# Driver log 
<img width="1686" alt="image" src="https://github.com/user-attachments/assets/9789c4f8-0fcc-40ad-9886-f8392b98ac6e">

**Comment by bluedenim** [comment]
If you are quitting a process, see this to shut down: https://github.com/bluedenim/log4j-s3-search-samples/blob/master/appender-log4j2-sample/src/main/java/com/van/example/Main.java#L43

**Comment by bluedenim** [comment]
There is no easy way for the event log thread to know when your program should end. Only your program knows when it's time to end.
