### ISSUE TITLE
S3 Configuration Documentation

### ISSUE THREAD

**Issue by Wiles** [bluedenim/log4j-s3-search#17]
Using:

    log4j.appender.S3Appender.s3AccessKey=
    log4j.appender.S3Appender.s3SecretKey=

Results in:

    log4j:WARN No such property [s3SecretKey] in org.van.logging.log4j.S3LogAppender.
    log4j:WARN No such property [s3AccessKey] in org.van.logging.log4j.S3LogAppender.
    
Instead I needed to use:

    log4j.appender.S3Appender.s3AwsKey=
    log4j.appender.S3Appender.s3AwsSecret=

**Comment by bluedenim** [comment]
Yes. Good catch. The source code is looking for `s3AwsKey` and `s3AwsSecret`.

https://github.com/bluedenim/log4j-s3-search/blob/master/s3loggerjar/src/main/java/org/van/logging/log4j/S3LogAppender.java#L148-L152

Sorry for the confusion. Hope it didn't waste too much of your time. :)

**Comment by bluedenim** [comment]
Fixed by https://github.com/bluedenim/log4j-s3-search/commit/e989c43627091c7b63bfa70035fde18cf7f08ec5.

**Comment by Wiles** [comment]
Thanks for the quick response.
