### ISSUE TITLE
where to get jar?

### ISSUE THREAD

**Issue by vimalprakashts** [bluedenim/log4j-s3-search#26]
hi where to get the jar is it available in maven?

**Comment by vanattf** [comment]
No. I've not published it into Maven, mostly because I don't know how. 😆 

The jars will have to be built manually for now. Should be easy to do, though. Just follow the instructions on the README.md.

**Comment by bluedenim** [comment]
I think you can now grab the jars from 
http://mvnrepository.com/search?q=com.therealvan

**Comment by bluedenim** [comment]
Specifically:
```
<dependency>
    <groupId>com.therealvan</groupId>
    <artifactId>appender-core</artifactId>
    <version>2.0.0</version>
</dependency>
```

Then, for the log4j bindings:
```
<dependency>
    <groupId>com.therealvan</groupId>
    <artifactId>appender-log4j</artifactId>
    <version>2.0.0</version>
</dependency>
```
or
```
<dependency>
    <groupId>com.therealvan</groupId>
    <artifactId>appender-log4j2</artifactId>
    <version>2.0.0</version>
</dependency>
```
