### ISSUE TITLE
I couldn't able to log the application log to the s3 

### ISSUE THREAD

**Issue by Gogulampati** [bluedenim/log4j-s3-search#27]
I can successfully log the custom logging into the s3 whereas i couldn't log the application log like spring boot log into s3. I couldn't find the s3 access key secret key terms in log4j2.xml how can i enable s3 in log4j2 sample without giving access key secret key.

**Comment by bluedenim** [comment]
If you're not running EC2, one way is to set up your AWS credentials in configuration files on your system (see 
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.htm for one way to set that up).
l
