### ISSUE TITLE
Publish to repository

### ISSUE THREAD

**Issue by Lapkritinis** [bluedenim/log4j-s3-search#29]
Any chance you could upload code to maven repository so I can include it as dependency in pom.xml.

Here is little howto:
https://dzone.com/articles/publish-your-artifacts-to-maven-central

Dependency could be included like:

        <dependency>
            <groupId>com.van</groupId>
            <artifactId>log4j-s3-search</artifactId>
            <version>2.0</version>
        </dependency>

**Comment by bluedenim** [comment]
Sure. Thanks for the link. I'll look into this.

**Comment by bluedenim** [comment]
WOOT!

http://mvnrepository.com/search?q=com.therealvan

2.0.0 is in Maven Central!

**Comment by bluedenim** [comment]
Oops. Spoke too early. Please wait for version `2.0.0`. Or plug `2.0.0` into the `<dependency><version>` element. E.g.
```
<dependency>
    <groupId>com.therealvan</groupId>
    <artifactId>appender-core</artifactId>
    <version>2.0.0</version>
</dependency>
```
and
```
<dependency>
    <groupId>com.therealvan</groupId>
    <artifactId>appender-log4j</artifactId>
    <version>2.0.0</version>
</dependency>
```
or
```
<dependency>
    <groupId>com.therealvan</groupId>
    <artifactId>appender-log4j2</artifactId>
    <version>2.0.0</version>
</dependency>
```

There are (or maybe) two other versions ("2.0" and "0.3.0"). Please ignore those two.
