### ISSUE TITLE
Not able to use jars directly as dependencies in another project

### ISSUE THREAD

**Issue by amol84** [bluedenim/log4j-s3-search#32]
First of all, thanks for creating this awesome project with a common and useful use case.

The problem I am facing is I am not able to use the jars appender-log4j2 and appender-core directly by including them as dependencies in pom.xml of my project as it complains parent project (log4j-s3-search) not found. I guess the only way to use my project is to add it as one of the modules in your parent pom, create a project inside your project just like your sample projects and build the parent pom. This will change the directory structure of my project which in turn will effect everyone in my organization.

Is there any easier way to integrate your jars directly with my project?

**Comment by bluedenim** [comment]
Hello,
Can you paste the dependencies for `appender-log4j2` and `appender-core` from your POM file?

I'd like to replicate what you're seeing.

Thanks!

**Comment by bluedenim** [comment]
I just did a quick test with a small program. I was able to use the JARs from mvn repo with this:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.van</groupId>
  <artifactId>log4j2test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>log4j2test</name>

  <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
            </configuration>
        </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.7</version>
    </dependency>

    <dependency>
      <groupId>com.therealvan</groupId>
      <artifactId>appender-core</artifactId>
      <version>2.0.0</version>
    </dependency>
    <dependency>
      <groupId>com.therealvan</groupId>
      <artifactId>appender-log4j2</artifactId>
      <version>2.0.0</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>

```

**Comment by amol84** [comment]
yes, it worked. I guess we have to add this dependency also the first time we build the project.
```
  <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.158</version>
        </dependency>
```

**Comment by bluedenim** [comment]
Hello. I'm not sure if the problem you experienced has anything to do with https://github.com/bluedenim/log4j-s3-search/issues/37

If you're still having problems, please use the latest release **2.1.1**.
