### ISSUE TITLE
Support different s3 provider

### ISSUE THREAD

**Issue by pwielgolaski** [bluedenim/log4j-s3-search#33]
It would be really cool to support different endpoint so you can use different provider i.e. 
https://www.digitalocean.com/community/questions/how-to-use-digitalocean-spaces-with-the-aws-s3-sdks

**Comment by bluedenim** [comment]
Version 2.1.0 of the libraries should now support two new S3 configuration parameters: **s3ServiceEndpoint** and **s3SigningRegion**. 
I believe these will give you what you want.
