### ISSUE TITLE
Incorrect example configuration documentation

### ISSUE THREAD

**Issue by Ulric19** [bluedenim/log4j-s3-search#40]
Unless i'm confusing the situation, there is an error in the documentation. Currently there is the following example for the log4j.properties file:
```log4j.appender.S3Appender=org.van.logging.log4j.S3LogAppender```
After some frustration in not being able to instantiate the class, I realized that the correct path to the class is this ```com.van.logging.log4j.Log4jAppender```

**Comment by bluedenim** [comment]
Yes. I switched to .com but forgot the docs. Sorry for your frustration. I will fix the docs.

**Comment by Ulric19** [comment]
Thank you for the fast response! I should have looked to the provided sample code sooner. Thanks so much for putting your time into this project.

**Comment by bluedenim** [comment]
Updated README.md to reflect the correct appender class: `com.van.logging.log4j.Log4jAppender`. Thanks!
