### ISSUE TITLE
SSE support

### ISSUE THREAD

**Issue by oshyshkin** [bluedenim/log4j-s3-search#41]
Hi. I'm trying to upload logs to S3 bucket with SSE (server-side encryption).
But I get an access denied error (for buckets without SSE everything is fine).

In my projects (on Kotlin), I use code like this:
```
val objectMetadata = ObjectMetadata()
objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION)
objectMetadata.setContentLength(content.length.toLong())

val putRequest = PutObjectRequest(targetBucketName,targetCsvS3Path, contentBytesStream, objectMetadata)
s3Client.putObject(putRequest)
```
However, I'm not sure how to apply it to your project.

**Comment by bluedenim** [comment]
Let me look into that

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bluedenim** [comment]
Aha! I think I need to do something similar to your
```
objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION)
```
somewhere around https://github.com/bluedenim/log4j-s3-search/blob/master/appender-core/src/main/java/com/van/logging/aws/S3PublishHelper.java#L105

I'll experiment a bit and update here my findings.

**Comment by oshyshkin** [comment]
I see. Thank you for a quick response!
It would be nice to have a possibility to config it from config file. Something like:
```
<sse>AES256</sse>
```
But it can have different values too. Not sure about all possible options but here are some docs regarding the topic:
https://docs.aws.amazon.com/AmazonS3/latest/dev/SSEUsingJavaSDK.html

**Comment by bluedenim** [comment]
Release 2.3.0 pushed to Maven. Can you verify? I've chosen to use the names from https://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html, so the config will be:
```
   <s3SseKeyType>SSE_S3</s3SseKeyType>
```
See https://github.com/bluedenim/log4j-s3-search/blob/master/appender-log4j2-sample/src/main/resources/log4j2.xml#L32

**Comment by oshyshkin** [comment]
Perfect! 
Yes, it works for me. Thank you for a quick update!
