### ISSUE TITLE
Reduce the amount of imported AWS SDK packages

### ISSUE THREAD

**Issue by NilsHasenbanck4758** [bluedenim/log4j-s3-search#46]
Hi,
We are currently optimizing our imports in our projects and happen to notice that your package seem to import the whole AWS 1.0 SDK (com.amazonaws.aws-java-sdk). Since this will import the whole SDK to the project, could you maybe consider only importing the needed S3 package (com.amazonaws.aws-java-sdk-s3)?

**Comment by bluedenim** [comment]
Sure. Let me look into that.

**Comment by bluedenim** [comment]
Version 2.3.1 now depends on aws-java-sdk-s3 only.
