### ISSUE TITLE
Role with Session Token

### ISSUE THREAD

**Issue by Jae32** [bluedenim/log4j-s3-search#49]
Hello,

My IAM role needs a session token along with key & secret key. Is it possible to define this in the properties?

**Comment by bluedenim** [comment]
I can add support for the session token. 

However, do note that, if you plan to run your code in EC2, it's probably easier to set up a role and assign it to your instance. See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html#using-temp-creds-sdk-ec2-instances

**Comment by bluedenim** [comment]
Version 2.4.0 now has support for a new property in logger configuration: s3AwsSessionToken 

NOTE that you will probably find it _easier_ to use the `.aws/credentials` file with the property `aws_session_token`. For example:

```
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
aws_session_token = AQoEXAMPLEH4aoAH0gNCAPyJxz4BlCFFxWNE1OPTgk5TthT+FvwqnKwRcOIfrRh3c/LTo6UDdyJwOOvEVPvLXCrrrUtdnniCEXAMPLE/IvU1dYUg2RVAJBanLiHb4IgRmpRV3zrkuWJOgQs8IZZaIv2BXIa2R4Olgk
```
