### ISSUE TITLE
Append logs in S3 and provide a file name pattern for file Creation

### ISSUE THREAD

**Issue by asifdiwan** [bluedenim/log4j-s3-search#52]
Hi @bluedenim 

I would like append logs to the S3 file which was created once the buffer limit was reached.
In my case the file was created when the buffer limit was reached first time. For next time file was not created or updated in S3.

So can you provide a way through which I can achieve the same.
Moreover I would want to provide file name pattern which should be followed while creating files in S3. Let me know if we can do that or not using any current properties.

**Comment by bluedenim** [comment]
Hello,

Appending to an existing log file:
Can you elaborate on your use case? It may be possible to use Multipart Upload to build up a large log file. But I suspect once that log file gets to a certain size, you will need to start a new file anyway lest you end up with one multi-terabyte file. Currently there is a parameter (e.g. adding `stagingBufferSize`) to set the size of the buffer before it uploads to S3. Will increasing that (e.g. `log4j.appender.S3Appender.stagingBufferSize=500000`) solve your use case?

Custom S3 key name pattern:
The pattern is currently set up to work with the S3 key list API to facilitate "paging" through the data in creation order. Did you just need to add some custom text to the key name, or do you have some other naming scheme in mind? Again, if you elaborate on what problem you're trying to solve with the name pattern, it'll help the discussion. Thanks!

**Comment by bluedenim** [comment]
Bump for more info please:

* Does increasing the buffer size (e.g. `stagingBufferSize`) solve your problem?
* What kind of expansion are you looking for in the key?

**Comment by bluedenim** [comment]
Closing on inactivity

**Comment by adinovriansyah** [comment]
Hi @bluedenim sorry to jump in, Relate to this issue? Maybe we can add suffix to filename (e.g. full key in S3 so it can be queried by Athena) ?
