### ISSUE TITLE
missing hostname in the S3 key format doc

### ISSUE THREAD

**Issue by yyamano** [bluedenim/log4j-s3-search#53]
https://github.com/bluedenim/log4j-s3-search/blob/master/README.md

> The final S3 key used in the bucket follows the format:
> 
> {s3Path}/yyyyMMddHH24mmss_{UUID w/ "-" stripped}

It must be {s3Path}/yyyyMMddHH24mmss_{hostname}_{UUID w/ "-" stripped}

**Comment by bluedenim** [comment]
Fixed. Thank you!
