### ISSUE TITLE
Feature request(s) to override default s3 path & allow ACLs

### ISSUE THREAD

**Issue by abhivijay89** [bluedenim/log4j-s3-search#68]
Hello @bluedenim,

I) Can we provide the flexibility of overriding the default s3 bucket path 'logs/' and allow upload of files/objects directly under the bucket? Currently, I see "log4j.appender.L4jAppender.s3Path" is a mandatory property - instead could we make this optional or allow empty value which allows publishing the files directly under the bucket along with the option of creating a custom directory structure too. We have a downstream system requirement which picks & processes files directly under a bucketname rather than following a custom directory structure. Raised a PR for the same, could you please review or suggest what would the most efficient way to achieve this?
**PR**: #https://github.com/bluedenim/log4j-s3-search/pull/67

II) Also, could we add option of allowing s3 ACLs? Due to restrictions imposed on our end, we need to push an object as below:
`PutObjectRequest por = new PutObjectRequest(bucket, key, file).withCannedAcl(CannedAccessControlList.BucketOwnerFullControl);`
instead of:
`PutObjectRequest por = new PutObjectRequest(bucket, key, file);`
**Reference**: https://github.com/bluedenim/log4j-s3-search/blob/master/appender-core/src/main/java/com/van/logging/aws/S3PublishHelper.java#L90

**Comment by bluedenim** [comment]
#67 merged. Thank you!

I'll look into the ACLs.

**Comment by abhivijay89** [comment]
Hey @bluedenim 
Raised PR #https://github.com/bluedenim/log4j-s3-search/pull/70 for including s3 acls. Please review and let me know if you would like me to make any changes.

**Comment by bluedenim** [comment]
I am a bit busy during the week. I will look at the PR when I get a chance. Thanks.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by abhivijay89** [comment]
Sure. Thanks!

**Comment by abhivijay89** [comment]
Thanks for reviewing the PR. I will work on the changes & get back.

**Comment by abhivijay89** [comment]
Incorporated the changes recommended by you => #70

**Comment by bluedenim** [comment]
#70 merged. Thanks!

Once #72 is merged, I'll do a release.
