### ISSUE TITLE
Refresh "s3Path" setting for S3Appender based on configuration

### ISSUE THREAD

**Issue by siri-rao** [bluedenim/log4j-s3-search#75]
I had one question about the configuration I am trying to create date wise folders using the “s3Path” element:
 
<s3Path>logs/messages/${date:YYYY-MM-dd}</s3Path>
 
Also I have set the “monitorInterval” attribute at the root Configuration element so that log4j configuration gets refreshed ( as per log4j documentation)
<Configuration monitorInterval="30">
 
But notice that the S3Path, once initialized, does not change unless the application is restarted. Is there anyway to refresh configuration once the monitorInterval has elapsed or by recognizing that value uses functions like ${date}

Thanks!

**Comment by bluedenim** [comment]
Just got time to look into this. From https://logging.apache.org/log4j/log4j-2.4/manual/configuration.html, I did notice that the monitorInterval triggers a "check for changes to the configuration file."

My guess is that, if the log4j2.xml file hasn't changed, then nothing will happen. How to trigger a reconfiguration depends on what Log4j2 interprets as change.
* If it's simply a change in the modified date, then something like a `touch .../log4j2.xml` cron'ed to run within the period specified by monitorInterval will work.
* If it's actually looking for a change in the contents, then you can try two versions of the file with some names (e.g. logger names) changed, and also have something like a script that swaps the two versions cron'ed up to run within the period specified by monitorInterval will work.

**Comment by siri-rao** [comment]
Hi Van,

Sorry for the late response, I had missed this email since it came into the
github associated email.

I was wondering if the S3 appender received a callback when the monitoring
interval elapsed? Also we deploy the application into a cloud platform and
do not have any handle on the log4j2 once the application is deployed,
unfortunately.

Would it be able to support any policies as part of the appender ( for
example, RollingFileAppender has a TimeBaseTriggeringPolicy). On my part I
will explore if I can write some LogInterceptors to see if we can update
the appender settings at runtime.

Thanks!
-Siri.

**Comment by bluedenim** [comment]
OK. I see. 

Let me think about this a bit to see if I can come up with something.

**Comment by bluedenim** [comment]
Tentative fix: https://github.com/bluedenim/log4j-s3-search/pull/78. I'm still testing.

**Comment by bluedenim** [comment]
Looks good from my testing. Both https://github.com/bluedenim/log4j-s3-search/pull/78 (this issue) and https://github.com/bluedenim/log4j-s3-search/pull/77 will be in the next release this weekend.

**Comment by bluedenim** [comment]
I used this format for the date expansion for the path:
`%d{yyyy_MM_dd_HH_mm_ss}`

There may be some restrictions on the characters used for the path/key for whichever cloud storage you're using (e.g. S3, Azure, GCS). Some may allow `-`, but `_` is safest.

**Comment by bluedenim** [comment]
Should be fixed by release 2.8.0

**Comment by siri-rao** [comment]
Van,

Thank you very much for the fix, would it be ok to use just the date part
from the pattern i.e.  %d{yyyy_MM_dd}?

Regards,
Siri.

**Comment by bluedenim** [comment]
Yes. It should be fine. Whatever works with PatternLayout (for date) should work since I’m using the same parser.


Van

**Comment by siri-rao** [comment]
Awesome, thank you!
