### ISSUE TITLE
LoggingEventCache shutdown hangs with <stagingBufferAge> set

### ISSUE THREAD

**Issue by abhivijay89** [bluedenim/log4j-s3-search#79]
Spark hangs indefinitely when 'stagingBufferAge' param is set. Observing this behaviour only when 'stagingBufferAge' is used but with "stagingBufferSize", it works perfectly fine.
Log snippet post shutdown hook trigger (hangs here):
```
LoggingEventCache: shutting down
LoggingEventCache: Executor service terminated within timeout: true
ExecutorService refused submitted task. Was shutDown() called?
```

**Comment by bluedenim** [comment]
Ooh. Interesting. I can look into that.

**Comment by bluedenim** [comment]
What is the age value you are using?

**Comment by bluedenim** [comment]
I think I know what's happening. The `TimePeriodBasedBufferMonitor` also has a thread executor in its implementation, so just like how the one in LoggingEventCache needs to `shutdown()`, it too needs it.

I'm going to see if I can reimplement the monitor w/o using a separate thread. It seemed like an easy/lazy way at the time. Either I reimplement it w/o a thread or create a global list of thread executors that need to be `shutdown` when the app ends.

**Comment by abhivijay89** [comment]
Sure. Thanks!

**Comment by bluedenim** [comment]
https://github.com/bluedenim/log4j-s3-search/pull/80 should fix this.

**Comment by bluedenim** [comment]
Release 2.8.1
