### ISSUE TITLE
While using the log4j2.xml configurations for Gcp bucket  I am getting invalid attributes error

### ISSUE THREAD

**Issue by kolipakaAbhinav** [bluedenim/log4j-s3-search#87]
Hi,
For a java project I want to write its logs into gcp-StorageBucket while trying it using the following maven dependencies 

```
-<dependency>
<groupId>com.therealvan</groupId>
<artifactId>appender-core</artifactId>
<version>2.6.0</version>
</dependency>


-<dependency>
<groupId>com.therealvan</groupId>
<artifactId>appender-log4j2</artifactId>
<version>2.6.0</version>
</dependency>
```

The  error I am getting is :

2020-11-12 16:16:11,945 main ERROR Log4j2Appender contains invalid attributes "gcpStorageBucket", "gcpStorageBlobNamePrefix"

Adding the log4j.xml for further reference
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>
        <RollingFile fileName="./logs/project.log"
                     filePattern="./logs/project_log-%d{MM-dd-yyyy}-%i.log"
                     name="A1">
            <PatternLayout>
                <Pattern>"%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"</Pattern>
            </PatternLayout>
            <Policies>
                <SizeBasedTriggeringPolicy size="1 GB"/>
            </Policies>
            <DefaultRolloverStrategy max="5"/>
        </RollingFile>
        <Log4j2Appender name="Log4j2Appender">
            <gcpStorageBucket>${env:GCP_STORAGE_BUCKET}</gcpStorageBucket>
            <gcpStorageBlobNamePrefix>logs/test</gcpStorageBlobNamePrefix>
            <gcpStorageCompressionEnabled>false</gcpStorageCompressionEnabled>
            <stagingBufferAge>60</stagingBufferAge>
            <PatternLayout pattern="%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n&quot;"/>
        </Log4j2Appender>
    </Appenders>
    <Loggers>
        <Root level="debug">
            <AppenderRef ref="A1"/>
            <AppenderRef ref="Console"/>
        </Root>
        <Logger level="debug" name="com.project_name" additivity="false">
            <AppenderRef ref="A1"/>
            <AppenderRef ref="Console"/>
            <AppenderRef ref="Log4j2Appender"/>
        </Logger>
    </Loggers>
</Configuration>


```

can you just brief a solution  for it ,Thank you

**Comment by bluedenim** [comment]
Thanks for the info. Let me take a look and get back to you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bluedenim** [comment]
Hm. I was **not** able to repro on my side with your log4j2.xml. I'm using the sample program from https://github.com/bluedenim/log4j-s3-search-samples:
- I cloned the repo 
- I replaced log4j-s3-search-samples/appender-log4j2-sample/src/main/resources/log4j2.xml with yours 
- I set the env variable GCP_STORAGE_BUCKET to my bucket on Google storage
- Then I built (`mvn install` at log4j-s3-search-samples root)
- Then I ran the sample program:
  - cd appender-log4j2-sample
  - java -cp target/log4j-s3-search-log4j2-sample.jar com.van.example.Main

The example program currently uses 2.8.3 of log4j-s3-search libraries. But even if I switched to 2.6.0 (modifying https://github.com/bluedenim/log4j-s3-search-samples/blob/master/pom.xml#L35 and rebuild), it still works (after commenting out https://github.com/bluedenim/log4j-s3-search-samples/blob/master/appender-log4j-sample/src/main/java/com/van/example/Main.java#L42 and https://github.com/bluedenim/log4j-s3-search-samples/blob/master/appender-log4j2-sample/src/main/java/com/van/example/Main.java#L43 since the `shutDown` function is not available for 2.6.0).

Maybe you're using a different version of Log4j2? Can you attach your project's pom.xml?

**Comment by kolipakaAbhinav** [comment]
Hmm,can you try with the log4j version I am using :

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.Project</groupId>
        <artifactId>project</artifactId>
        <version>2.2.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.project</groupId>
    <artifactId>project</artifactId>
    <version>2.2.0</version>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
                <groupId>org.apache.maven.plugins</groupId>
                <version>3.8.1</version>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                            <appendAssemblyId>false</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.11</artifactId>
            <version>0.11.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>com.therealvan</groupId>
            <artifactId>appender-core</artifactId>
            <version>2.7.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.therealvan</groupId>
            <artifactId>log4j-s3-search</artifactId>
            <version>2.8.3</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>com.therealvan</groupId>
            <artifactId>appender-log4j2</artifactId>
            <version>2.7.0</version>
        </dependency>
    </dependencies>
</project>

**Comment by bluedenim** [comment]
OK. Looking at your POM. It looks like you're using **Log4j 2.11.2**?

The current release of com.therealvan:appender-log4j2 (or even release 2.7.0 as you have it above) is built and tested with **Log4j 2.13.2**.

So firstly: I think you should modify the log4j-s3-search libs imported. You don't need to add com.therealvan:log4j-s3-search or even com.therealvan:appender-core; this is all you need:
```
        <dependency>
            <groupId>com.therealvan</groupId>
            <artifactId>appender-log4j2</artifactId>
            <version>2.8.3</version>
        </dependency>
```
Because of transitive dependency (i.e. appender-log4j2 depends on appender-core), you can just use the above.

(I encourage you to use the latest com.therealvan:appender-log4j2:2.8.3 because it has a bunch of bug fixes.)

You can look at how my example program is done here: https://github.com/bluedenim/log4j-s3-search-samples/blob/master/appender-log4j2-sample/pom.xml

Secondly: if I am to start with your POM, I would edit it to this:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.Project</groupId>
        <artifactId>project</artifactId>
        <version>2.2.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.project</groupId>
    <artifactId>project</artifactId>
    <version>2.2.0</version>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
                <groupId>org.apache.maven.plugins</groupId>
                <version>3.8.1</version>
            </plugin>
            <!-- Maven Assembly Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                            <appendAssemblyId>false</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.11</artifactId>
            <version>0.11.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.13.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.13.2</version>
        </dependency>

        <dependency>
            <groupId>com.therealvan</groupId>
            <artifactId>appender-log4j2</artifactId>
            <version>2.8.3</version>
        </dependency>
    </dependencies>
</project>
```

Can you try the above and see if it solves your problem?

**Comment by kolipakaAbhinav** [comment]
Yes, I will try making the changes you suggested and let you know .

**Comment by bluedenim** [comment]
Someone else also had trouble getting started. I created a super simple example and attached it there: https://github.com/bluedenim/log4j-s3-search/issues/88

It may also help get you started. You can add more dependencies and code to experiment.

**Comment by kolipakaAbhinav** [comment]
My issue got solved after for adding  maven shade plugin in pom.xml as mentioned in the issue [https://github.com/bluedenim/log4j-s3-search/issues/88](url)
